name: NERFeatures

# Data
load_ner_features: True
save_ner_features: False

# Features
num_ner_segments: 40
use_seg_t_features: False

# Arch
feature_dim: 16
num_linear_layers: 0
linear_layer_size: 512
intermediate_layer_size: 16
num_attention_layers: 6
n_head: 8
separate_seg_and_class_heads: False

# Training
epochs: 50
batch_size: 128
learning_rate: 1e-3

print_interval: 100
eval_interval: 200
eval_samples: 3200


