name: SegmentTransformer

# Data
load_ner_features: True
save_ner_features: False

# Features
num_ner_segments: 40
use_seg_t_features: True

# Arch
feature_dim: 768
num_linear_layers: 0
linear_layer_size: 512
intermediate_layer_size: 768
use_roberta: True
num_attention_layers: 6
n_head: 8
separate_seg_and_class_heads: False

# Training
epochs: 50
batch_size: 128
learning_rate: 3e-5

print_interval: 100
eval_interval: 200
eval_samples: 3200
