name: classification

epochs: 200
lr: 1e-3
batch_size: 128

batches_per_eval: 16
print_interval: 100
eval_interval: 500

max_discourse_elements: 32

num_attention_layers: 2
nhead: 8
num_linear_layers: 3
linear_layer_size: 512
intermediate_layer_size: 64
dropout: 0.3

use_correct_segments: False
debug: False
wandb: True
seed: 0