name: ner

essay_max_tokens: 1024

linear_layers: 3
linear_layer_size: 512


lr: 2e-5
epochs: 3
batch_size: 1
grad_accumulation: 32
max_grad_norm: 10


print_interval: 10
eval_interval: 50
eval_samples: 512


save_model: True
debug: False
wandb: True
seed: 0
