name: ppo

train_ner_model: False
ner_model_name: woven-wood-3

layer_size: 1024
n_layers: 5

total_timesteps: 1e6
n_steps: 256
batch_size: 512
n_envs: 12

save_ner_probs: False
load_ner_probs: True

save_model: True
sync_tensorboard: True
sb3_verbosity: 1