name: segmentation

train_ner_model: False
ner_model_name: firm-monkey-1

layer_size: 512
n_layers: 3

total_timesteps: 1e6
n_steps: 32
batch_size: 32
n_envs: 12

save_model: True
sync_tensorboard: True
sb3_verbosity: 1