name: sac

train_ner_model: False
ner_model_name: vibrant-wildflower-3

layer_size: 512
n_layers: 3

total_timesteps: 1e6
batch_size: 32
n_envs: 1

save_model: True
sync_tensorboard: True
sb3_verbosity: 1