name: ppo

saved_model_name: 'hardy-aardvark-57_fold_0_hardy-aardvark-57'

total_timesteps: 1e7
n_steps: 128
batch_size: 512
n_envs: 12
lr: 3e-4
epochs: 10
target_kl: 0.1

save_model: True
sync_tensorboard: True
sb3_verbosity: 1