name: ppo

feature_extractor: SegmentAttention
num_attention_layers: 2
n_head: 6


layer_size: 512
n_layers: 1

total_timesteps: 1e7
n_steps: 128
batch_size: 512
n_envs: 12
lr: 1e-3
epochs: 10


save_model: True
sync_tensorboard: True
sb3_verbosity: 1